# Cross-package parity: R's Cytoscape network exports (.graphml + .sif) must
# byte-match the webtool/Python goldens in
# python/tests/fixtures/expected/*__network.{graphml,sif}.
#
# The goldens are generated by scripts/generate-parity-fixtures.mts from the
# live TypeScript toGraphml()/toSif(); Python reproduces them byte-for-byte
# and this file asserts the R package does too. Each golden filename encodes
# the sample and the model: "<sample>__<model>__network.<ext>".
#
# dataset_mock_streaming_platforms used to be the documented divergence
# (duplicate "Dark Matter" rows); since v2.7.0 the webapp loader dedupes by
# identifier too, so the golden matches everywhere.

.fixtures_dir <- function() {
    here <- testthat::test_path()
    candidates <- c(
        file.path(here, "..", "..", "..", "python", "tests", "fixtures", "expected"),
        file.path(here, "..", "..", "fixtures", "expected")
    )
    for (cand in candidates) {
        if (dir.exists(cand)) return(normalizePath(cand))
    }
    NULL
}

# Parse "<sample>__<model>__network.<ext>" -> list(sample, model).
.parse_network_fixture <- function(fname, ext) {
    stem <- sub(paste0("__network\\.", ext, "$"), "", fname)
    parts <- strsplit(stem, "__", fixed = TRUE)[[1L]]
    list(sample = parts[1L], model = parts[2L])
}

.read_golden_bytes <- function(path) {
    size <- file.info(path)$size
    con <- file(path, open = "rb")
    on.exit(close(con))
    rawToChar(readBin(con, what = "raw", n = size))
}

fixtures_dir <- .fixtures_dir()

if (!is.null(fixtures_dir)) {
    graphml_goldens <- list.files(fixtures_dir, pattern = "__network\\.graphml$")
    sif_goldens <- list.files(fixtures_dir, pattern = "__network\\.sif$")
} else {
    graphml_goldens <- character(0L)
    sif_goldens <- character(0L)
}

for (gname in graphml_goldens) {
    local({
        parsed <- .parse_network_fixture(gname, "graphml")
        sample <- parsed$sample
        model  <- parsed$model
        golden <- file.path(fixtures_dir, gname)

        test_that(sprintf("network GraphML parity (bytes): %s [%s]", sample, model), {
            skip_on_cran()
            skip_if(is.null(fixtures_dir), "webtool fixtures not available")
            res <- analyze(load_sample(sample), model = model)
            actual <- .network_graphml_string(.build_network_data(res))
            expected <- .read_golden_bytes(golden)
            expect_identical(actual, expected)
        })
    })
}

for (gname in sif_goldens) {
    local({
        parsed <- .parse_network_fixture(gname, "sif")
        sample <- parsed$sample
        model  <- parsed$model
        golden <- file.path(fixtures_dir, gname)

        test_that(sprintf("network SIF parity (bytes): %s [%s]", sample, model), {
            skip_on_cran()
            skip_if(is.null(fixtures_dir), "webtool fixtures not available")
            res <- analyze(load_sample(sample), model = model)
            actual <- .network_sif_string(.build_network_data(res))
            expected <- .read_golden_bytes(golden)
            expect_identical(actual, expected)
        })
    })
}

test_that("write methods produce the same bytes as the string helpers", {
    skip_on_cran()
    res <- analyze(load_sample("dataset_real_cancer_drivers_4"), model = "venn-4-set")
    data <- .build_network_data(res)

    graphml_path <- tempfile(fileext = ".graphml")
    to_network_graphml(res, graphml_path)
    expect_identical(.read_golden_bytes(graphml_path), .network_graphml_string(data))

    sif_path <- tempfile(fileext = ".sif")
    to_network_sif(res, sif_path)
    expect_identical(.read_golden_bytes(sif_path), .network_sif_string(data))
})

test_that("at least the 5 network goldens (graphml + sif) are discovered", {
    skip_on_cran()
    skip_if(is.null(fixtures_dir), "webtool fixtures not available")
    expect_gte(length(graphml_goldens), 5L)
    expect_gte(length(sif_goldens), 5L)
})
